services:
  divide:
    image: ghcr.io/haenrick/divide:latest
    restart: unless-stopped
    ports:
      - "${PORT:-3050}:${PORT:-3050}"
    volumes:
      - divide-data:/data
    env_file:
      - .env
    mem_limit: 128m
    memswap_limit: 128m

volumes:
  divide-data:
